NAME-ROHAN SRIVASTAV <br>
Data Science January MAJOR Project(2022-23)<br>
SMARTKNOWERS

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import GridSearchCV

In [2]:
df=pd.read_csv('adult (1).csv')
df.shape

(32560, 15)

In [3]:
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

<br>

#RENAMING THE COLUMNS

In [4]:
df.columns=['Age',
 'Workclass',
 'Fnlwgt',
 'Education',
 'education_num',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital_gain',
 'capital_loss',
 'hours_per_week',
 'native_country',
 'income'          ]

In [5]:
df.columns

Index(['Age', 'Workclass', 'Fnlwgt', 'Education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [6]:
df.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Age             32560 non-null  int64 
 1   Workclass       32560 non-null  object
 2   Fnlwgt          32560 non-null  int64 
 3   Education       32560 non-null  object
 4   education_num   32560 non-null  int64 
 5   marital_status  32560 non-null  object
 6   occupation      32560 non-null  object
 7   relationship    32560 non-null  object
 8   race            32560 non-null  object
 9   sex             32560 non-null  object
 10  capital_gain    32560 non-null  int64 
 11  capital_loss    32560 non-null  int64 
 12  hours_per_week  32560 non-null  int64 
 13  native_country  32560 non-null  object
 14  income          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


#There are no NULL vaues, Data imputation is not required

<br>


#CHECKING FOR DUPLICATE DATA

In [8]:
df.duplicated().value_counts()

False    32536
True        24
dtype: int64

In [9]:
df[df.duplicated()]

Age          Workclass  Fnlwgt      Education  education_num  \
4880    25            Private  308144      Bachelors             13   
5103    90            Private   52386   Some-college             10   
9170    21            Private  250051   Some-college             10   
11630   20            Private  107658   Some-college             10   
13083   25            Private  195994        1st-4th              2   
15058   21            Private  243368      Preschool              1   
17039   46            Private  173243        HS-grad              9   
18554   30            Private  144593        HS-grad              9   
18697   19            Private   97261        HS-grad              9   
21317   19            Private  138153   Some-college             10   
21489   19            Private  146679   Some-college             10   
21874   49            Private   31267        7th-8th              4   
22299   25            Private  195994        1st-4th              2   
22366   44            Private  367749      Bachelors             13   
22493   49   Self-emp-not-inc   43479   Some-college             10   
25871   23            Private  240137        5th-6th              3   
26312   28            Private  274679        Masters             14   
28229   27            Private  255582        HS-grad              9   
28521   42            Private  204235   Some-college             10   
28845   39            Private   30916        HS-grad              9   
29156   38            Private  207202        HS-grad              9   
30844   46            Private  133616   Some-college             10   
31992   19            Private  251579   Some-college             10   
32403   35            Private  379959        HS-grad              9   

            marital_status          occupation    relationship  \
4880         Never-married        Craft-repair   Not-in-family   
5103         Never-married       Other-service   Not-in-family   
9170         Never-married      Prof-specialty       Own-child   
11630        Never-married        Tech-support   Not-in-family   
13083        Never-married     Priv-house-serv   Not-in-family   
15058        Never-married     Farming-fishing   Not-in-family   
17039   Married-civ-spouse        Craft-repair         Husband   
18554        Never-married       Other-service   Not-in-family   
18697        Never-married     Farming-fishing   Not-in-family   
21317        Never-married        Adm-clerical       Own-child   
21489        Never-married     Exec-managerial       Own-child   
21874   Married-civ-spouse        Craft-repair         Husband   
22299        Never-married     Priv-house-serv   Not-in-family   
22366        Never-married      Prof-specialty   Not-in-family   
22493   Married-civ-spouse        Craft-repair         Husband   
25871        Never-married   Handlers-cleaners   Not-in-family   
26312        Never-married      Prof-specialty   Not-in-family   
28229        Never-married   Machine-op-inspct   Not-in-family   
28521   Married-civ-spouse      Prof-specialty         Husband   
28845   Married-civ-spouse        Craft-repair         Husband   
29156   Married-civ-spouse   Machine-op-inspct         Husband   
30844             Divorced        Adm-clerical       Unmarried   
31992        Never-married       Other-service       Own-child   
32403             Divorced       Other-service   Not-in-family   

                      race      sex  capital_gain  capital_loss  \
4880                 White     Male             0             0   
5103    Asian-Pac-Islander     Male             0             0   
9170                 White   Female             0             0   
11630                White   Female             0             0   
13083                White   Female             0             0   
15058                White     Male             0             0   
17039                White     Male             0             0   
18554                Black     Male         

<br>

#DROPPING DUPLICATE ROWS

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().value_counts()

False    32536
dtype: int64

In [12]:
df.shape

(32536, 15)

<br>

#LABEL ENCODING (CATEGORICAL TO NUMERICAL)

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [14]:
categorical_columns=['Workclass','Education','marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
  'native_country',
 'income'                   ]

In [15]:
for i in categorical_columns:
    df[i]=le.fit_transform(df[i])

In [16]:
df.head()

Age  Workclass  Fnlwgt  Education  education_num  marital_status  \
0   50          6   83311          9             13               2   
1   38          4  215646         11              9               0   
2   53          4  234721          1              7               2   
3   28          4  338409          9             13               2   
4   37          4  284582         12             14               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           4             0     4    1             0             0   
1           6             1     4    1             0             0   
2           6             0     2    1             0             0   
3          10             5     2    0             0             0   
4           4             5     4    0             0             0   

   hours_per_week  native_country  income  
0              13              39       0  
1              40              39       0  
2              40              39       0  
3              40               5       0  
4              40              39       0

NOTE-IN INCOME COLUMN, 0 REPRESENTS LESS THAN OR EQUAL TO 50K AND 1 REPRESENTS MORE THAN 50K

<br>

#NORMALISING THE NUMERICAL DATA COLUMNS

In [17]:
for i in df.columns:
    if i not in categorical_columns:
        mean=df[i].mean(axis=0)
        std=df[i].std(axis=0)
        df[i]=(df[i]-mean)/std
        

In [18]:
df.head()

Age  Workclass    Fnlwgt  Education  education_num  marital_status  \
0  0.836948          6 -1.008688          9       1.134800               2   
1 -0.042934          4  0.245004         11      -0.420639               0   
2  1.056919          4  0.425713          1      -1.198359               2   
3 -0.776169          4  1.408014          9       1.134800               2   
4 -0.116257          4  0.898078         12       1.523659               2   

   occupation  relationship  race  sex  capital_gain  capital_loss  \
0           4             0     4    1     -0.145966     -0.216743   
1           6             1     4    1     -0.145966     -0.216743   
2           6             0     2    1     -0.145966     -0.216743   
3          10             5     2    0     -0.145966     -0.216743   
4           4             5     4    0     -0.145966     -0.216743   

   hours_per_week  native_country  income  
0       -2.222416              39       0  
1       -0.035664              39       0  
2       -0.035664              39       0  
3       -0.035664               5       0  
4       -0.035664              39       0

<br>

#SPLITTING THE DATA INTO TRAINING AND TESTING

In [19]:
from sklearn.model_selection import train_test_split
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test = train_test_split(x,y)
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((24402, 14), (24402,), (8134, 14), (8134,))

<br>

#FUNCTION FOR PREDICTING AND DISPLAYING CONFUSION MATRIX AND CLASSIFICATION REPORT

In [20]:
from sklearn.metrics import classification_report,confusion_matrix

In [21]:
def prediction_summary(classifier_object):
    model=classifier_object.fit(x_train,y_train)
    print("TRAINING ACCURACY IS-",model.score(x_train,y_train)*100)
    print(" ")
    print("TESTIN ACCURACY IS-",model.score(x_test,y_test)*100)
    print(" ")
    y_pred=model.predict(x_test)
    print("CONFUSION MATRIX -")
    print(confusion_matrix(y_test,y_pred))
    print(" ")
    print("CLASSIFICATION REPORT -")
    print(classification_report(y_test,y_pred))   
    return y_pred

<br>

#CLASSIFYING USING GAUSSIAN NAIVE BAYES CLASSIFIER

In [49]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()

In [50]:
gnb_prediction=prediction_summary(gb)

TRAINING ACCURACY IS- 80.10818785345464
 
TESTIN ACCURACY IS- 81.16547823948856
 
CONFUSION MATRIX -
[[5905  316]
 [1216  697]]
 
CLASSIFICATION REPORT -
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      6221
           1       0.69      0.36      0.48      1913

    accuracy                           0.81      8134
   macro avg       0.76      0.66      0.68      8134
weighted avg       0.80      0.81      0.79      8134



<br>

#CLASSIFYING USING DECISION TREE CLASSIFIER

In [51]:
from sklearn.tree import DecisionTreeClassifier

HYPERPARAMETER TUNING USING GRID SEARCH CV

In [58]:
dt=DecisionTreeClassifier()


In [ ]:
dt_params_grid={
    'criterion':['gini','entropy'],
    'max_depth':[2,3,4,5],
    'min_samples_split':[10,15,20,25,30,35,40]
}

In [59]:
dt_gscv=GridSearchCV(dt,param_grid=dt_params_grid)

In [61]:
dt_gscv.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5],
                         'min_samples_split': [10, 15, 20, 25, 30, 35, 40]})

In [64]:
print(dt_gscv.best_params_)
print(dt_gscv.best_estimator_)

{'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 30}
DecisionTreeClassifier(max_depth=5, min_samples_split=30)


In [68]:
dt=DecisionTreeClassifier(criterion='entropy',max_depth=5, min_samples_split=30)
dt_prediction=prediction_summary(dt)

TRAINING ACCURACY IS- 84.63240717973936
 
TESTIN ACCURACY IS- 85.01352348168183
 
CONFUSION MATRIX -
[[5921  300]
 [ 919  994]]
 
CLASSIFICATION REPORT -
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      6221
           1       0.77      0.52      0.62      1913

    accuracy                           0.85      8134
   macro avg       0.82      0.74      0.76      8134
weighted avg       0.84      0.85      0.84      8134



NOTE-ON USING CRITERION AS ENTROPY , TESTING ACCURACY WAS COMING 1 % MORE THAN WITH GINI AS CRITERON(TRAINING ACCURACY WAS ALMOST SAME)

#CLASSIFYING USING RANDOM FOREST CLASSIFIER

In [76]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [78]:
rf_params_grid={
    'n_estimators':[10,15,20,25,30],
    'criterion':['gini','entropy'],
    'max_depth':[2,3,4,5],
    'min_samples_split':[5,7,10,15,20,25,30,35,40]
}

In [79]:
rf_gscv=GridSearchCV(rf,param_grid=rf_params_grid)

In [80]:
rf_gscv.fit(x_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5],
                         'min_samples_split': [5, 7, 10, 15, 20, 25, 30, 35,
                                               40],
                         'n_estimators': [10, 15, 20, 25, 30]})

In [81]:
print(rf_gscv.best_params_)
print(rf_gscv.best_estimator_)

{'criterion': 'gini', 'max_depth': 5, 'min_samples_split': 15, 'n_estimators': 30}
RandomForestClassifier(max_depth=5, min_samples_split=15, n_estimators=30)


In [86]:
rf=RandomForestClassifier(criterion='gini',max_depth=5, min_samples_split=15, n_estimators=30)

In [87]:
rf_prediction=prediction_summary(rf)

TRAINING ACCURACY IS- 84.93156298664044
 
TESTIN ACCURACY IS- 85.32087533808705
 
CONFUSION MATRIX -
[[5965  256]
 [ 938  975]]
 
CLASSIFICATION REPORT -
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      6221
           1       0.79      0.51      0.62      1913

    accuracy                           0.85      8134
   macro avg       0.83      0.73      0.76      8134
weighted avg       0.85      0.85      0.84      8134



#CLASSIFYING USING LOGISTIC REGRESSION

In [106]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=180)
lr_prediction=prediction_summary(lr)

TRAINING ACCURACY IS- 82.39488566510941
 
TESTIN ACCURACY IS- 82.77600196705188
 
CONFUSION MATRIX -
[[5827  394]
 [1007  906]]
 
CLASSIFICATION REPORT -
              precision    recall  f1-score   support

           0       0.85      0.94      0.89      6221
           1       0.70      0.47      0.56      1913

    accuracy                           0.83      8134
   macro avg       0.77      0.71      0.73      8134
weighted avg       0.82      0.83      0.82      8134



#CLASSIFYING USING K-NEAREST NEIGHBOURS

In [113]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

#HYPERAMETER TUNING

In [114]:
knn_params_grid={
    'n_neighbors':[5,6,7,8,9,10,11,12,13,14,15]
}

In [115]:
knn_gscv=GridSearchCV(knn,param_grid=knn_params_grid)

In [116]:
knn_gscv.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                                         15]})

In [117]:
print(knn_gscv.best_params_)
print(knn_gscv.best_estimator_)

{'n_neighbors': 12}
KNeighborsClassifier(n_neighbors=12)


In [120]:
knn=KNeighborsClassifier(n_neighbors=12)
knn_prediction=prediction_summary(knn)

TRAINING ACCURACY IS- 85.12826817473977
 
TESTIN ACCURACY IS- 82.97270715515121
 
CONFUSION MATRIX -
[[5748  473]
 [ 912 1001]]
 
CLASSIFICATION REPORT -
              precision    recall  f1-score   support

           0       0.86      0.92      0.89      6221
           1       0.68      0.52      0.59      1913

    accuracy                           0.83      8134
   macro avg       0.77      0.72      0.74      8134
weighted avg       0.82      0.83      0.82      8134



#CONCLUSION

THE PREDICTIONS FROM VARIOUS MODELS ARE GIVEN BELOW-

In [ ]:
gnb_prediction        #Gaussian Naive Bayes Classifier
dt_prediction         #Decision Tree Classifier
rf_prediction         # Random Forest Classifier
lr_prediction         #Logistic Regression
knn_prediction        #K-Neighbors Classifier

THE MODEL WHICH GAVE THE BEST TESTING ACCURACY IS ->RANDOM FOREST CLASSIFIER

THANK YOU!<br>
THE END